on:
  # runs on any push that does NOT contain a tag
  push:
    branches:
      - trunk
    tags-ignore:
      - '*'

name: CI

env:
  CARGO_TERM_COLOR: always

jobs:

  tests:
    name: Build & Test
    uses: ./.github/workflows/tests.yml 

